version: "3"
services:
  spark:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: spark-hudi
    ports:
      - "8888:8888"
      - "4041:4041"
      - "4040:4040"
      - "18080:18080"
    volumes:
      - ./app:/home/sparkuser/app
      - ./app/event_logs:/home/spark/event_logs
    command: jupyter
    depends_on:
      - minio
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - S3_ENDPOINT=http://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - SPARK_DRIVER_MEMORY=2G
      - SPARK_WORKER_MEMORY=2G
      - SPARK_EXECUTOR_MEMORY=2G
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"  # Minio Console
    volumes:
      - ./minio/data:/data  # Persistent storage
      - ./minio/config:/root/.minio  # Configurations
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
